@echo off
chcp 65001 > nul
echo Удаление ненужных системных компонентов...
echo =========================================
echo Удаляем папку Globalization...
rd /s /q "C:\Windows\Globalization" 2>nul
echo Удаляем временные файлы...
rd /s /q "C:\Windows\Temp" 2>nul
rd /s /q "C:\Windows\Prefetch" 2>nul
echo Удаляем кэш локализации...
rd /s /q "C:\Windows\System32\IME" 2>nul
echo.
echo Оптимизация завершена! Перезагрузка через 5 секунд...
timeout /t 5 /nobreak > nul
shutdown /r /t 0 /f
